#!/usr/bin/env bash
# ShellSpec test runner for Bazel
# This script is generated by the shellspec_test rule.

set -eu

# Ensure HOME is set (shellspec requires it)
export HOME="${HOME:-/tmp}"

# =============================================================================
# Sharding Check
# =============================================================================
# ShellSpec does not support Bazel's test sharding mechanism.
# If sharding is enabled, we must fail immediately with a clear error.
if [[ -n "${TEST_TOTAL_SHARDS:-}" ]] && [[ "${TEST_TOTAL_SHARDS}" -gt 1 ]]; then
    echo "ERROR: shellspec_test does not support test sharding." >&2
    echo "ShellSpec runs all specs as a single test suite and cannot partition tests." >&2
    echo "Please remove 'shard_count' from your test target or set it to 1." >&2
    exit 1
fi

# =============================================================================
# Coverage Check
# =============================================================================
# ShellSpec uses kcov for coverage, which is not bundled and requires
# system installation. Warn the user if coverage is requested but kcov
# is not available.
if [[ -n "${COVERAGE:-}" ]] && [[ "${COVERAGE}" == "1" ]]; then
    if ! command -v kcov &>/dev/null; then
        echo "WARNING: Coverage was requested but 'kcov' is not installed." >&2
        echo "ShellSpec requires kcov for shell script coverage reporting." >&2
        echo "Coverage data will not be collected for this test." >&2
        echo "To install kcov, see: https://github.com/SimonKagwortz/kcov" >&2
        echo "" >&2
    fi
fi

# =============================================================================
# Environment Setup
# =============================================================================
# Change to the runfiles directory where test files are available
if [[ -n "${TEST_SRCDIR:-}" ]]; then
    cd "${TEST_SRCDIR}/${TEST_WORKSPACE:-}"
fi

# Create a .shellspec file if it doesn't exist to satisfy shellspec's project requirement
if [[ ! -f .shellspec ]]; then
    touch .shellspec
fi

# =============================================================================
# Build ShellSpec Arguments
# =============================================================================
SHELLSPEC_ARGS=()

# Set the shell to use
SHELL_OPT="{{SHELL}}"
if [[ -n "${SHELL_OPT}" ]] && [[ "${SHELL_OPT}" != "/bin/sh" ]]; then
    SHELLSPEC_ARGS+=("--shell" "${SHELL_OPT}")
fi

# Output format and JUnit XML output for Bazel test result integration
# ShellSpec uses -f for display formatter and -o for report output
SHELLSPEC_ARGS+=("--format" "progress")

# If XML_OUTPUT_FILE is set, generate JUnit report to the report directory
# and then copy it to the expected location
if [[ -n "${XML_OUTPUT_FILE:-}" ]]; then
    REPORT_DIR=$(dirname "${XML_OUTPUT_FILE}")
    SHELLSPEC_ARGS+=("--reportdir" "${REPORT_DIR}")
    SHELLSPEC_ARGS+=("--output" "junit")
fi

# Add any custom shellspec options
CUSTOM_OPTS="{{SHELLSPEC_OPTS}}"
if [[ -n "${CUSTOM_OPTS}" ]]; then
    # shellcheck disable=SC2086
    SHELLSPEC_ARGS+=(${CUSTOM_OPTS})
fi

# Add the spec files
SPEC_FILES="{{SPEC_FILES}}"

# =============================================================================
# Execute ShellSpec
# =============================================================================
SHELLSPEC_BIN="{{SHELLSPEC_BIN}}"

# Run shellspec with the collected arguments
# shellcheck disable=SC2086
exec "${SHELLSPEC_BIN}" "${SHELLSPEC_ARGS[@]}" ${SPEC_FILES}
