#!/usr/bin/env bash
# ShellSpec test runner for Bazel
# This script is generated by the shellspec_test rule.

set -eu

# Ensure HOME is set (shellspec requires it)
export HOME="${HOME:-/tmp}"

# =============================================================================
# Sharding Check
# =============================================================================
# ShellSpec does not support Bazel's test sharding mechanism.
# If sharding is enabled, we must fail immediately with a clear error.
if [[ -n "${TEST_TOTAL_SHARDS:-}" ]] && [[ "${TEST_TOTAL_SHARDS}" -gt 1 ]]; then
    echo "ERROR: shellspec_test does not support test sharding." >&2
    echo "ShellSpec runs all specs as a single test suite and cannot partition tests." >&2
    echo "Please remove 'shard_count' from your test target or set it to 1." >&2
    exit 1
fi

# =============================================================================
# Coverage Check
# =============================================================================
# ShellSpec uses kcov for coverage, which is not bundled and requires
# system installation. Warn the user if coverage is requested but kcov
# is not available.
if [[ -n "${COVERAGE:-}" ]] && [[ "${COVERAGE}" == "1" ]]; then
    if ! command -v kcov &>/dev/null; then
        echo "WARNING: Coverage was requested but 'kcov' is not installed." >&2
        echo "ShellSpec requires kcov for shell script coverage reporting." >&2
        echo "Coverage data will not be collected for this test." >&2
        echo "To install kcov, see: https://github.com/SimonKagstrom/kcov" >&2
        echo "" >&2
    fi
fi

# =============================================================================
# Runfiles Setup
# =============================================================================
# Set up the runfiles environment for the bash runfiles library

# --- begin runfiles.bash initialization v3 ---
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v3 ---

# Export runfiles variables so spec_helper.sh can use them
export RUNFILES_DIR
export RUNFILES_MANIFEST_FILE

# =============================================================================
# Environment Setup
# =============================================================================
# Change to the runfiles directory where test files are available
if [[ -n "${TEST_SRCDIR:-}" ]]; then
    cd "${TEST_SRCDIR}/${TEST_WORKSPACE:-}"
fi

# Set up the generated .shellspec config file
SHELLSPEC_CONFIG="{{SHELLSPEC_CONFIG}}"

# Create a .shellspec file for this run
if [[ -n "${SHELLSPEC_CONFIG}" ]] && [[ -f "${SHELLSPEC_CONFIG}" ]]; then
    # If there's already a .shellspec, back it up
    if [[ -f .shellspec ]] && [[ ! -L .shellspec ]]; then
        mv .shellspec .shellspec.bak
    fi
    # Copy the config to the current directory
    cp "${SHELLSPEC_CONFIG}" .shellspec
else
    # Create a minimal .shellspec if none provided
    touch .shellspec
fi

# =============================================================================
# Build ShellSpec Arguments
# =============================================================================
SHELLSPEC_ARGS=()

# Set the shell to use
SHELL_OPT="{{SHELL}}"
if [[ -n "${SHELL_OPT}" ]]; then
    SHELLSPEC_ARGS+=("--shell" "${SHELL_OPT}")
fi

# Output format and JUnit XML output for Bazel test result integration
# ShellSpec uses -f for display formatter and -o for report output
SHELLSPEC_ARGS+=("--format" "progress")

# If XML_OUTPUT_FILE is set, generate JUnit report to the report directory
# and then copy it to the expected location
if [[ -n "${XML_OUTPUT_FILE:-}" ]]; then
    REPORT_DIR=$(dirname "${XML_OUTPUT_FILE}")
    SHELLSPEC_ARGS+=("--reportdir" "${REPORT_DIR}")
    SHELLSPEC_ARGS+=("--output" "junit")
fi

# Add any custom shellspec options
CUSTOM_OPTS="{{SHELLSPEC_OPTS}}"
if [[ -n "${CUSTOM_OPTS}" ]]; then
    # shellcheck disable=SC2086
    SHELLSPEC_ARGS+=(${CUSTOM_OPTS})
fi

# Add the spec files
SPEC_FILES="{{SPEC_FILES}}"

# =============================================================================
# Execute ShellSpec
# =============================================================================
SHELLSPEC_BIN="{{SHELLSPEC_BIN}}"

# Run shellspec with the collected arguments
# shellcheck disable=SC2086
exec "${SHELLSPEC_BIN}" "${SHELLSPEC_ARGS[@]}" ${SPEC_FILES}
